# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-13 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='titulo',
            field=models.CharField(max_length=20, null=True, verbose_name='Titulo'),
        ),
    ]
